### ISSUE TITLE
order by date asc or desc

### ISSUE THREAD

**Issue by nowfalsalahudeen** [dariopellegrini/StorageDone-Android#3]
how can i write order by date asc or desc

**Comment by dariopellegrini** [comment]
Ordering is not yet supported on database layer, but it's coming on the next release.
In the mean time you can sort using Kotlin list sorting
```
list.sortBy{ it.date }
list.sortByDescending{ it.date }
```

Thank you.

**Comment by dariopellegrini** [comment]
Added on v0.6.

```kotlin
val orderedTeachers = database.get<Teacher>("dateCreated".ascending)
```

**Comment by nowfalsalahudeen** [comment]
will check it out and let you know.Thanks for your fast action

**Comment by dariopellegrini** [comment]
Try to check advanced queries as well.
More information [here](https://github.com/dariopellegrini/StorageDone-Android#advanced-queries).
