### ISSUE TITLE
No attribute for AutoIncrement Primary key or id

### ISSUE THREAD

**Issue by nowfalsalahudeen** [dariopellegrini/StorageDone-Android#4]
is there any option for make id(primaryKey) as  AutoIncrement or unique id?

**Comment by dariopellegrini** [comment]
Cause we're on a NoSQL database, a UUID should be preferred to an auto-incremented integer id.
Can I suggest something like this?
```kotlin
data class Teacher(val id: String = UUID.randomUUID().toString(),
                   val name: String?,
                   val surname: String?,
                   val age: Int?,
                   val cv: String?): PrimaryKey {
    override fun primaryKey(): String {
        return "id"
    }
}
```

If you still need for an auto-incremented ID I could check for its feasibility.

Let me know and thank you.
