### ISSUE TITLE
Not saving Array<MyObjects>

### ISSUE THREAD

**Issue by Luisalfredrod** [dariopellegrini/StorageDone-Android#5]
There is an issue with a warning probably i forgot a step but it doesn't save myObject:
W/CouchbaseLite/DATABASE: Database.log.getFile().getConfig() is null, meaning file logging is disabled. Log files required for product support are not being generated.

**Comment by dariopellegrini** [comment]
Hello @Luisalfredrod 
That warning is not related with the Array issue.
Use List instead of array and it should work.

In the next release I'll support array and remove that warning. If you still need arrays I'm keeping this issue open until then.

Thank you for your feedback.
