### ISSUE TITLE
After updating the library I'm facing this issue

### ISSUE THREAD

**Issue by Taimoor-Azam** [dariopellegrini/StorageDone-Android#9]
Cannot create database configuration.  Did you forget to call CouchbaseLite.init()?

**Comment by dariopellegrini** [comment]
If you're using the library after 0.7 you have to make these changes.

From
```kotlin
val database = StorageDoneDatabase(context, "teachers")
```

To
```kotlin
// In Application class
override fun onCreate() {
   super.onCreate()
   ...
   StorageDoneDatabase.configure(this)
}

val database = StorageDoneDatabase("teachers")
```

In this way, you are free from context dependency.

Hope this helps.

Thank you.

**Comment by Taimoor-Azam** [comment]
Thanks . Now It's working
